### ISSUE TITLE
Tests failing in MacOS

### ISSUE THREAD

**Issue by ljwoods2** [Becksteinlab/imdreader#1]
GROMACS must install differently on mac, requires investigation

**Comment by orbeckst** [comment]
This looks like a bug in the cf package (see eg https://github.com/Becksteinlab/imdreader/actions/runs/9538170351/job/26287049912#step:5:33 )

>  /Users/runner/miniconda3/envs/imdreader-test/etc/conda/activate.d/gromacs_activate.sh: line 22: /Users/runner/miniconda3/envs/imdreader-test/bin./GMXRC: No such file or directory

There's a `.` after `bin` in the path.

**Comment by ljwoods2** [comment]
This appears to be caused by the macOS-latest having an arm64 architecture. This is what I think is happening:

in `/Users/runner/miniconda3/envs/imdreader-test/etc/conda/activate.d/gromacs_activate.sh`:

```
#! /bin/bash

function _gromacs_bin_dir() {
  local simdflavor
  local uname=$(uname -m)
  if [[ "$uname" == "arm64" ]]; then
    # Assume ARM Mac
    test -d "/Users/runner/miniconda3/envs/imdreader-test/bin.ARM_NEON_ASIMD" &&
       simdflavor='ARM_NEON_ASIMD'
  else
    simdflavor='SSE2'
    case $( sysctl -a | grep '^hw.optional\..*: 1$' ) in
      *\ avx2\ * | *avx2_0*)
        test -d "/Users/runner/miniconda3/envs/imdreader-test/bin.AVX2_256" &&
         simdflavor='AVX2_256'
      ;;
      *\ avx\ * | *avx1_0*)
        test -d "/Users/runner/miniconda3/envs/imdreader-test/bin.AVX_256" &&
        simdflavor='AVX_256'
    esac
  fi
  printf '%s' "/Users/runner/miniconda3/envs/imdreader-test/bin.${simdflavor}"
}

. "$( _gromacs_bin_dir )/GMXRC" "${@}"
```

These lines are causing the issue:
```
  local uname=$(uname -m)
  if [[ "$uname" == "arm64" ]]; then
```

`uname -m` evaluates to "arm64", but, the conda environment was configured to download x64 binaries and use rosetta (not super familiar with this) to run them on the mac runner with the arm64 arch. So in the 
`/Users/runner/miniconda3/envs/imdreader-test/` path we have `bin.AVX2_256`, `bin.AVX_256` and `bin.SSE2` (which were dowloaded from conda) but not `bin.ARM_NEON_ASIMD` as would be expected. 

To fix this, I think this step `gh-ci.yaml` will have to change:

```
    - name: Install conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: devtools/conda-envs/test_env.yaml
        add-pip-as-python-dependency: true
        architecture: x64

        channels: conda-forge, defaults

        activate-environment: imdreader-test
        auto-update-conda: true
        auto-activate-base: false
        show-channel-urls: true
        miniconda-version: latest
```

Related: https://github.com/actions/runner-images?tab=readme-ov-file#available-images
